server:
  port: 8090

spring:
  application:
    name: msvc-student
  datasource: #configuracion del driver de postgresql
    url: jdbc:postgresql://localhost:5432/studentDb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # Puedes usar 'create', 'update', 'validate' o 'none'

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka