server:
  port: 9090

spring:
  application:
    name: msvc-course
  datasource: #configuracion del driver de postgresql
    url: jdbc:postgresql://localhost:5432/coursesDb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka